version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/app/src
      - ./nodemon.json:/usr/app/nodemon.json
    container_name: ts-node-docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npm run dev:docker"
    restart: always
