version: '3.8'
services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: admier
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db