version: "3.8"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: prismatest
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/app/src
      - ./nodemon.json:/usr/app/nodemon.json
    container_name: ts-node-docker
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npx prisma generate && npm run dev:docker"
    restart: always